initial travis ci test for opensuse leap

diff --git a/.travis/rpmbuild_test b/.travis/rpmbuild_test
--- a/.travis/rpmbuild_test
+++ b/.travis/rpmbuild_test
@@ -2,28 +2,56 @@
 
 # this script runs as root under docker 
 
-OS_VERSION="$1"
+OS_TYPE="$1"
+OS_VERSION="$2"
 
 # build and install
-yum install -y libtool rpm-build make squashfs-tools openssl-devel libuuid-devel
+if [ "$OS_TYPE" = "centos" ]; then
+    install_autogen_reqs="
+        yum install -y libtool rpm-build make yum-utils
+    "
+    install_configure_reqs="
+        yum-builddep singularity.spec
+    "
+    install_test_reqs="
+        yum install -y epel-release
+        yum install -y python34 python34-pip python34-setuptools docker
+        yum install -y pylint
+        yum install -y sudo which e2fsprogs
+    "
+elif [ "$OS_TYPE" = "opensuse" ]; then
+    install_autogen_reqs="
+        zypper install -y --no-recommends libtool rpm-build
+    "
+    install_configure_reqs="
+        zypper install -y --no-recommends $(rpmspec -q --buildrequires singularity.spec)
+    "
+    install_test_reqs="
+        zypper install -y --no-recommends python3 python3-pip python3-setuptools docker
+        zypper install -y --no-recommends python3-pylint
+        zypper install -y --no-recommends sudo which e2fsprogs
+    "
+else
+    echo "Cannot rpmbuild on $OS_TYPE"
+    exit 1
+fi
+
+eval "$install_autogen_reqs"
 ./autogen.sh
+eval "$install_configure_reqs"
 ./configure
 make dist
 rpmbuild -ta *.tar.gz
 rpm -iv ~/rpmbuild/RPMS/*/*.rpm
 
-if [ "$OS_VERSION" = 6 ]; then
+if [ "$OS_TYPE" = "centos" ] && [ "$OS_VERSION" = 6 ]; then
     echo "the test suite has not yet been ported to centos6 python, skipping."
     exit
 fi
 
-# Install python 3 and pylint
-yum install -y epel-release
-yum install -y python34 python34-pip python34-setuptools docker
-yum install -y pylint
+eval "$install_test_reqs"
 
 # run the test suite
-yum install -y libtool sudo which e2fsprogs
 sed -i 's,^prefix=.*,prefix=/usr,' test.sh
 sed -i 's,^sysconfdir=.*,sysconfdir=/etc,' test.sh
 sed -i 's,^localstatedir=.*,localstatedir=/var,' test.sh
